### PR TITLE
[parser] add a guard for realloc failure

### PR DESCRIPTION
**Pull request by justinjoy**
Normally, we don't expect to see realloc failure, but it is possible
when running in harsh condition.

### CODE REVIEW

**Comment by justinjoy** [comment]
hmm, dropping coverage rate causes failure? I am not sure how I can interpret this result.

**Comment by loganek** [comment]
Hi @justinjoy Thanks sooo much for the contribution, I totally agree with that change. I normally don't check memory allocation problems in a parser library, because this code (as opposite of the library code) is expected to be run on quite high-end developer desktops. Also, the library uses a lot of C++ standard library data structures like hash maps or vectors that might fail to allocate memory, but in that case they throw `std::bad_alloc` - we never capture that, TBH there's not much we can do in case of the out-of-memory error. 
However, I think capturing `realloc` failure in C code is a good practice, as it helps a lot with the debugging this kind of errors. I'm only wondering, whether we should return `false` from that function, or rather throw `std::bad_alloc` as all the other code do. What do you think? 

Regarding code coverage - the `if` branch that you modified wasn't covered at all, so when you added more lines to that branch, the code coverage slightly dropped (as now we have even more not-covered code). Would be awesome if you could write a test that covers this scenario, but if you don't, it's fine, I can override the rule and merge the PR anyway :)

**Comment by justinjoy** [comment]
Definitely, throwing exception is better than checking by return value.

But, regarding unittest, I don't know how I can simulate malloc/realloc failure without adding real memory consumer. Any hint to write the test code?

**Comment by loganek** [comment]
@justinjoy Thanks a lot for the contribution!

**Comment by justinjoy** [comment]
thank you for warm greeting. :)

**Pull request merged**
